#! /bin/bash
#To store information
#Created by Ktsg
#01/10/19

echo "Enter Name";
read name;
echo "Enter m1:"
read m1;
echo "Enter m2";
read m2;
echo "Enter m3"
read m3;
tot=`expr $m1 + $m2 + $m3`;
per=`expr $tot / 3`;
echo $name $tot $per >> a2;
